### ISSUE TITLE
Question: 怎么打印这个文档，或者怎么输出pdf文件？

### ISSUE THREAD

**Issue by Yensan** [apachecn/spark-doc-zh#183]
谢谢你们翻译文档，我们小组觉得很好，想整个打印出来。
我们可以怎样做呢？

**Comment by Kylin1027** [comment]
如果是直接打印 markdown 文档的话, 可以使用 chrome 浏览器->打印-> 更改 -> 另存为 PDF 的功能,  然后打印 pdf 文件就行了.

**Comment by Yensan** [comment]
@Kylin1027  问题是这个文件太多了……

**Comment by Kylin1027** [comment]
@Yensan 这样哦, 要不一起加入一起帮忙整理下文档吧 ~

**Comment by wizardforcel** [comment]
这个项目用的页面生成器是 jekyll，好像不支持生成pdf。

**Comment by Kylin1027** [comment]
我理解是不是有一份目录索引就好?  pdf 打印的话, 只要是 markdown 格式ok通过浏览器重定向成 pdf 格式就可以的

**Comment by Yensan** [comment]
写一个 Python，然后遍历文件目录/文件夹，然后 调用 pandoc 转为 pdf……

**Comment by chenzhenguo** [comment]
同求
