### ISSUE TITLE
跳转404

### ISSUE THREAD

**Issue by ghost** [apachecn/spark-doc-zh#194]
http://spark.apachecn.org/#/docs/3
入门第一页   ： 您可以直接从 Dataset 中获取 values（值），通过调用一些 actions（动作），或者 transform（转换）Dataset 以获得一个新的。更多细节，请参阅 【API doc】。这里点链接会跳转到http://spark.apachecn.org/#/api/scala/index.html?id=org.apache.spark.sql.dataset，显示404
![image](https://user-images.githubusercontent.com/20885056/67203508-d8dc2800-f43d-11e9-98e1-f1b8c086b120.png)

**Comment by mapengfei2016** [comment]
> http://spark.apachecn.org/#/docs/3
> 入库第一页 ： 您可以直接从 Dataset 中获取 values（值），通过调用一些 actions（动作），或者 transform（转换）Dataset 以获得一个新的。更多细节，请参阅 【API doc】。这里点链接会跳转到[http://spark.apachecn.org/#/api/scala/index.html?id=org.apache.spark.sql.dataset，显示404](http://spark.apachecn.org/#/api/scala/index.html?id=org.apache.spark.sql.dataset%EF%BC%8C%E6%98%BE%E7%A4%BA404)
> ![image](https://user-images.githubusercontent.com/20885056/67203508-d8dc2800-f43d-11e9-98e1-f1b8c086b120.png)
