### ISSUE TITLE
跳转404

### ISSUE THREAD

**Issue by ghost** [apachecn/spark-doc-zh#195]
http://spark.apachecn.org/#/docs/3
入门第一页 ： 您可以直接从 Dataset 中获取 values（值），通过调用一些 actions（动作），或者 transform（转换）Dataset 以获得一个新的。更多细节，请参阅 【API doc】。这里点链接会跳转到http://spark.apachecn.org/#/api/scala/index.html?id=org.apache.spark.sql.dataset，显示404
![image](https://user-images.githubusercontent.com/20885056/67203616-22c50e00-f43e-11e9-8139-0261a6bb28a3.png)

**Comment by ghost** [comment]
http://spark.apachecn.org/#/api/python/index.html?id=pyspark.sql.column
![image](https://user-images.githubusercontent.com/20885056/67205193-c532c080-f441-11e9-9fb8-2c1b0ee816ee.png)
"的参数都是 Column 里的  "  这里也是404

**Comment by jiangzhonglian** [comment]
这些链接好像都取消了，变成 docs/1...n

api 相关的内容的确没有翻译，编译过程太麻烦了
